apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron
  namespace: dapr-python-reference
annotations:
  dapr.io/config: "daprConfig"  
spec:
  type: bindings.cron
  version: v1
  metadata:
  - name: schedule
    value: "@every 60s" # valid cron schedule