apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: task-secrets
  namespace: dapr-python-reference
annotations:
  dapr.io/config: "daprConfig"  
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../dapr/components/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - task-service